# Generated by Django 3.2.6 on 2021-08-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentation',
            old_name='URL',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='documentation',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
