# Generated by Django 3.2.6 on 2021-08-26 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('team', '0001_initial'),
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='supplier',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
            preserve_default=False,
        ),
    ]
