# Generated by Django 3.2.6 on 2021-08-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyevent',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
