name: Backend

on: [push]

jobs:
  build-backend:

    runs-on: ubuntu-latest
    env:
      backend-directory: ./backend

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ${{env.backend-directory}}
    - name: Run migrations
      run: python manage.py migrate
      working-directory: ${{env.backend-directory}}
    - name: Run tests
      run: python manage.py test
      working-directory: ${{env.backend-directory}}

   build-frontend:

    runs-on: ubuntu-latest
    env:
      frontend-directory: ./frontend

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install
      working-directory: ${{env.frontend-directory}}
    - name: Run build
      run: yarn run build --if-present
      working-directory: ${{env.frontend-directory}}
    - name: Run tests
      run: yarn test
      working-directory: ${{env.frontend-directory}}