name: Backend

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      backend-directory: ./backend

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
      working-directory: ${{env.backend-directory}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ${{env.backend-directory}}
    - name: Run migrations
      run: python manage.py migrate
      working-directory: ${{env.backend-directory}}
    - name: Run tests
      run: python manage.py test
      working-directory: ${{env.backend-directory}}